In [4]:
import numpy as np

In [5]:
my_list = [10, 20, 30, 40]

In [6]:
type(my_list)

list

In [7]:
my_numpy_array = np.array(my_list)

In [8]:
type(my_numpy_array)

numpy.ndarray

In [9]:
my_numpy_array.max()

np.int64(40)

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.random.random(5)

array([0.0214018 , 0.74042144, 0.30821974, 0.50675531, 0.37422843])