In [3]:
import numpy as np

In [4]:
my_list = [10, 20, 30, 40]

In [5]:
type(my_list)

list

In [6]:
my_numpy_array = np.array(my_list)

In [7]:
type(my_numpy_array)

numpy.ndarray

In [8]:
my_numpy_array.max()

np.int64(40)

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.random.random(5)

array([0.14465566, 0.24936588, 0.71572666, 0.6729307 , 0.23716237])

ARRAY ARITHMETIC

In [12]:
my_list1 = [1, 2] 

In [13]:
my_list2 = [2, 3]

In [14]:
my_list1 + my_list2

[1, 2, 2, 3]

In [15]:
my_numpy_array1 = np.array(my_list1)

In [16]:
my_numpy_array2 = np.array(my_list2)

In [17]:
my_numpy_array1 + my_numpy_array2

array([3, 5])

In [18]:
my_numpy_array1 * my_numpy_array2

array([2, 6])

In [19]:
my_numpy_array1 - my_numpy_array2

array([-1, -1])

In [20]:
my_numpy_array1 / my_numpy_array2

array([0.5       , 0.66666667])

In [21]:
my_numpy_array1 * 5

array([ 5, 10])

In [22]:
other_array = np.array([10, 20, 30, 40, 50])

In [23]:
other_array.min()

np.int64(10)

In [24]:
other_array.sum()  

np.int64(150)

INDEX

In [25]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
np_array = np.arange(0, 10)

In [28]:
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np_array[0]

np.int64(0)

In [30]:
np_array[-1]

np.int64(9)

In [31]:
np_array[1:4:]

array([1, 2, 3])

In [32]:
np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [33]:
np_array[2:6:2]

array([2, 4])

In [34]:
np.random.randn(4)

array([-1.08751699,  1.23829818,  1.37597714, -0.27223709])

In [35]:
np.random.randn(4, 4)

array([[ 0.93813175,  0.67750663, -0.04396894, -1.94456098],
       [ 2.01614809,  0.69733806, -1.15830466, -0.81266769],
       [-1.10886965,  0.97648564,  0.25798823,  0.87077539],
       [ 1.26883608, -1.60344252,  0.81625826, -0.9250091 ]])

In [36]:
np.random.randint(1, 300, 5)

array([ 56, 152, 102,  22, 214], dtype=int32)

MATRIX

In [37]:
numpy_matrix = np.array([[5, 10], [15, 20]])

In [38]:
numpy_matrix

array([[ 5, 10],
       [15, 20]])

In [39]:
numpy_matrix[1][0]

np.int64(15)

In [40]:
# Dot Product

In [41]:
first_matrix = np.array([[10, 20, 30]])

In [42]:
first_matrix

array([[10, 20, 30]])

In [44]:
first_matrix.shape

(1, 3)

In [45]:
second_matrix = np.array([[1, 2], [3, 4], [5, 6]])

In [46]:
second_matrix.shape

(3, 2)

In [47]:
# In Numpy, the dot method is used for dot product operations.
first_matrix.dot(second_matrix)

array([[220, 280]])