In [5]:
import numpy as np

In [6]:
my_list = [10, 20, 30, 40]

In [7]:
type(my_list)

list

In [8]:
my_numpy_array = np.array(my_list)

In [9]:
type(my_numpy_array)

numpy.ndarray

In [10]:
my_numpy_array.max()

np.int64(40)

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.random.random(5)

array([0.85739117, 0.92717798, 0.35943805, 0.02093761, 0.23760703])

ARRAY ARITHMETIC

In [14]:
my_list1 = [1, 2] 

In [15]:
my_list2 = [2, 3]

In [16]:
my_list1 + my_list2

[1, 2, 2, 3]

In [17]:
my_numpy_array1 = np.array(my_list1)

In [18]:
my_numpy_array2 = np.array(my_list2)

In [19]:
my_numpy_array1 + my_numpy_array2

array([3, 5])

In [20]:
my_numpy_array1 * my_numpy_array2

array([2, 6])

In [21]:
my_numpy_array1 - my_numpy_array2

array([-1, -1])

In [22]:
my_numpy_array1 / my_numpy_array2

array([0.5       , 0.66666667])

In [23]:
my_numpy_array1 * 5

array([ 5, 10])

In [24]:
other_array = np.array([10, 20, 30, 40, 50])

In [25]:
other_array.min()

np.int64(10)

In [26]:
other_array.sum()  

np.int64(150)

INDEX

In [27]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
np_array = np.arange(0, 10)

In [30]:
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np_array[0]

np.int64(0)

In [32]:
np_array[-1]

np.int64(9)

In [33]:
np_array[1:4:]

array([1, 2, 3])

In [34]:
np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [35]:
np_array[2:6:2]

array([2, 4])

In [36]:
np.random.randn(4)

array([ 0.68931959,  0.51376818, -1.82265992,  0.65799405])

In [37]:
np.random.randn(4, 4)

array([[-1.45746751,  1.07420069, -0.66024958, -0.13331877],
       [ 0.87610146,  1.25894537, -1.31347099, -0.90150363],
       [-0.18032431,  1.46205267,  0.98236812, -0.82319247],
       [-0.61806459, -0.71362299, -0.74103033, -1.45306331]])

In [38]:
np.random.randint(1, 300, 5)

array([183, 151, 220, 178, 221], dtype=int32)

MATRIX

In [39]:
numpy_matrix = np.array([[5, 10], [15, 20]])

In [40]:
numpy_matrix

array([[ 5, 10],
       [15, 20]])

In [41]:
numpy_matrix[1][0]

np.int64(15)